ffmpeg -f x11grab \
    -thread_queue_size 256 \
    -video_size 950x400 \
    -framerate 8 \
    -i :0.0 \
    -f pulse \
    -thread_queue_size 512 \
    -i alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo.monitor \
    -c:v h264_omx \
    -b:v 400k \
    -r 8 \
    -c:a aac \
    -b:a 48k \
    -ar 44100 \
    -ac 1 \
    -f flv "rtmp://a.rtmp.youtube.com/live2/YOUR_API_KEY"
